---
- name: Install and start apache
  hosts: web
  tasks:
   - name: Ensure the httpd package is installed  
     ansible.builtin.yum:
            name: httpd
            state: present
            
   - name: create index.html file
     ansible.builtin.template:
            src: files/index.html
            dest: /var/www/html
            
   - name: Start the httpd service if needed
     ansible.builtin.service:
             name: httpd
             state: started
             
   - name: allow port 80 from firewall
     ansible.builtin.firewalld:
          service: http
          permanent: yes
          immediate: yes
          state: enabled
    
